"""Add environment fields

Revision ID: 7c9b585ff9f5
Revises: e447b3b67e54
Create Date: 2026-03-16 03:18:17.132927
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '7c9b585ff9f5'
down_revision: Union[str, None] = 'e447b3b67e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('area_sqm', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('road_type', sa.String(length=50), nullable=True))
    op.add_column('reports', sa.Column('weather', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'weather')
    op.drop_column('reports', 'road_type')
    op.drop_column('reports', 'area_sqm')
    # ### end Alembic commands ###
