"""Add width and depth to reports

Revision ID: e447b3b67e54
Revises: 
Create Date: 2026-03-16 03:08:20.007917
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'e447b3b67e54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('width_cm', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('depth_cm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'depth_cm')
    op.drop_column('reports', 'width_cm')
    # ### end Alembic commands ###
